#!/usr/bin/env python3
"""Bake the corpus-over-time histogram (role-stacked bars) from data/papers.json
into index.html between <!-- HISTOGRAM:START --> / <!-- HISTOGRAM:END -->."""
import json
import re
from collections import defaultdict
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
papers = json.loads((SITE / "data" / "papers.json").read_text())

ROLES = ["perception", "reasoning", "action", "datasets"]
COLORS = {"perception": "var(--moss-fill)", "reasoning": "var(--ochre-fill)",
          "action": "var(--terra-fill)", "datasets": "var(--data-fill)"}
LABELS = {"perception": "Perception", "reasoning": "Reasoning",
          "action": "Action", "datasets": "Datasets"}

counts = defaultdict(lambda: defaultdict(int))
for m in papers["methods"]:
    if m["year"]:
        counts[m["year"]][m["role"]] += 1
for d in papers["datasets"]:
    if d["year"]:
        counts[d["year"]]["datasets"] += 1

years = sorted(counts)
y0, y1 = years[0], years[-1]
years = list(range(y0, y1 + 1))
totals = {y: sum(counts[y].values()) for y in years}
peak_year = max(totals, key=totals.get)

W, H = 1180, 300
PADL, PADR, PADT, PADB = 20, 20, 42, 40
bw_slot = (W - PADL - PADR) / len(years)
bw = bw_slot * 0.62
maxn = max(totals.values())
scale = (H - PADT - PADB) / maxn

bars, labels = [], []
for i, y in enumerate(years):
    x = PADL + i * bw_slot + (bw_slot - bw) / 2
    base = H - PADB
    for role in ROLES:
        n = counts[y].get(role, 0)
        if not n:
            continue
        h = n * scale
        base -= h
        bars.append(f'<rect x="{x:.1f}" y="{base:.1f}" width="{bw:.1f}" height="{h:.1f}" fill="{COLORS[role]}" rx="1"/>')
    if y % 2 == 0 or len(years) < 16:
        labels.append(f'<text class="hg-x" x="{x + bw / 2:.1f}" y="{H - PADB + 20}" text-anchor="middle">{"’" + str(y)[2:]}</text>')
    if y == peak_year:
        labels.append(
            f'<text class="hg-peak" x="{x + bw / 2:.1f}" y="{base - 12:.1f}" text-anchor="middle">{totals[y]}</text>'
            f'<circle cx="{x + bw / 2:.1f}" cy="{base - 30:.1f}" r="0" />')

legend = "".join(
    f'<g transform="translate({PADL + i * 150} 18)">'
    f'<rect width="10" height="10" y="-9" fill="{COLORS[r]}" rx="1"/>'
    f'<text class="hg-leg" x="16" y="0">{LABELS[r]}</text></g>'
    for i, r in enumerate(ROLES))

svg = f'''<svg viewBox="0 0 {W} {H}" role="img" aria-label="Papers per year, stacked by role; {peak_year} peaks at {totals[peak_year]}.">
  <style>
    .hg-x, .hg-leg, .hg-peak {{ font-family: "JetBrains Mono", monospace; fill: var(--ink-muted); }}
    .hg-x {{ font-size: 12px; letter-spacing: .04em; }}
    .hg-leg {{ font-size: 12.5px; letter-spacing: .08em; }}
    .hg-peak {{ font-size: 14px; fill: var(--ink); font-weight: 500; }}
  </style>
  <line x1="{PADL}" y1="{H - PADB}" x2="{W - PADR}" y2="{H - PADB}" stroke="var(--line)" stroke-width="1"/>
  {legend}
  {''.join(bars)}
  {''.join(labels)}
</svg>
<figcaption class="media-block__meta">
  <span class="media-block__label">Fig. 03 · The corpus over time</span>
  <span class="media-block__caption">Surveyed methods and datasets per year, stacked by role — the field accelerates sharply after 2022, peaking in {peak_year}.</span>
</figcaption>'''

block = f'''<!-- HISTOGRAM:START (generated by tools/build_histogram.py) -->
        {svg}
        <!-- HISTOGRAM:END -->'''

index = SITE / "index.html"
html = index.read_text(encoding="utf-8")
new, n = re.subn(r"<!-- HISTOGRAM:START.*?<!-- HISTOGRAM:END -->", block, html, flags=re.S)
if n != 1:
    raise SystemExit(f"expected 1 HISTOGRAM block, found {n}")
index.write_text(new, encoding="utf-8")
print(f"histogram: {y0}–{y1}, peak {peak_year} ({totals[peak_year]})")
