#!/usr/bin/env python3
"""Render the hero author block from tools/authors.json into index.html
between <!-- AUTHORS:START --> / <!-- AUTHORS:END --> markers. Idempotent."""
import json
import re
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
SITE = TOOLS.parent
data = json.loads((TOOLS / "authors.json").read_text(encoding="utf-8"))

parts = []
for a in data["authors"]:
    sup = "".join(str(n) for n in a["affils"]) + "".join(a["marks"])
    name = a["name"]
    inner = f'<a href="{a["url"]}" target="_blank" rel="noopener">{name}</a>' if a.get("url") else name
    parts.append(f'<span class="author">{inner}<sup>{sup}</sup></span>')
authors_html = "\n        ".join(parts)

def affil_html(n, a):
    if isinstance(a, str):  # legacy plain-string form
        a = {"name": a}
    logo = ""
    if a.get("logo"):
        logo = (f'<img class="affil__logo" src="assets/logos/{a["logo"]}" '
                f'width="{a["w"]}" height="{a["h"]}" alt="" decoding="async" />')
    return f'<span class="affil">{logo}<i class="affil__num">{n}</i>{a["name"]}</span>'

affils_html = "\n        ".join(affil_html(n, a) for n, a in data["affiliations"].items())
marks_html = " ".join(
    f'<span class="mark"><b>{m}</b>{label}</span>' for m, label in data["marks"].items()
)

block = f"""<!-- AUTHORS:START (generated by tools/build_authors.py — edit tools/authors.json, not this) -->
      <p class="hero__authors">
        {authors_html}
      </p>
      <div class="hero__affils">
        {affils_html}
      </div>
      <p class="hero__marks">{marks_html}</p>
      <!-- AUTHORS:END -->"""

index = SITE / "index.html"
html = index.read_text(encoding="utf-8")
new, n = re.subn(r"<!-- AUTHORS:START.*?<!-- AUTHORS:END -->", block, html, flags=re.S)
if n != 1:
    raise SystemExit(f"expected exactly 1 AUTHORS marker block, found {n}")
index.write_text(new, encoding="utf-8")
print(f"injected {len(data['authors'])} authors")
